FROM leplusorg/kali:latest

RUN apt-get update && apt install -y iproute2 iputils-ping git python3 python3-pip

COPY simple_https.py /simple-https-python-server/simple_https.py
COPY skynet.gif /simple-https-python-server/skynet.gif
COPY submit.html /simple-https-python-server/submit.html