FROM nginx:latest

RUN mkdir /usr/share/nginx/html/submit

COPY c2_config.c2 /etc/nginx/conf.d/default.conf
COPY cyberdemologo.jpeg /usr/share/nginx/html/submit/cyberdemologo.jpeg
COPY index.html /usr/share/nginx/html/index.html
COPY bannerlogo.png /usr/share/nginx/html/bannerlogo.png
COPY illustration.png /usr/share/nginx/html/illustration.png
COPY submit.html /usr/share/nginx/html/submit/index.html

RUN apt-get update && apt install -y iproute2 iputils-ping openssl net-tools
RUN openssl req -x509 -nodes -days 365 -newkey rsa:4096 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt -subj "/C=US/ST=MD/O=CyberSecurityDemo/OU=IT/CN=presentation.com"